services:
  stock:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0 
    volumes:
      - ./app:/app
      - ./app/data:/app/data