apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: stock-db
  name: stock-db
  namespace: egs-fuellink
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi